spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url : jdbc:h2:mem:minulog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8090
custom:
  data:
    human:
      name: yong
      age: 35
      address: seoul