spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url : jdbc:h2:mem:minulog
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
server:
  port: 8090

devlog:
  jwt-key: "ja1klZJDfYdvTPPfI0tEoFyGo2u4ty10EaDiEc85sz0="