### 회원가입
POST http://localhost:8090/auth/signup
Content-Type: application/json

{
  "email": "dodok@gmail.com",
  "password": 12345,
  "name" : "김도독"
}

### 로그인
POST http://localhost:8090/auth/login
Content-Type: application/x-www-form-urlencoded

username=dodok@gmail.com&password=12345&remember=1

### 인증페이지 요청
GET http://localhost:8090/posts/auth
Content-Type: application/json