### 로그인

POST http://localhost:8090/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=1234&remember=1

### 인증페이지 요청
GET http://localhost:8090/posts/auth
Content-Type: application/json